### ISSUE TITLE
Login should not be required for `doctor`, `--version` ("ERROR: must login first" + traceback)

### ISSUE THREAD

**Issue by soulshake** [convox/rack#1408]
```
$ convox -v
client: 20161118150327
ERROR: must login first
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x13a490]

goroutine 1 [running]:
panic(0x58ae60, 0xc42000e050)
/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/convox/rack/client.(*Client).request(0x0, 0x62cf1a, 0x3, 0x6301d7, 0x7, 0x0, 0x0, 0x5ebec0, 0xc4201ae680, 0x32)
/tmp/release.jHJRd/src/github.com/convox/rack/client/client.go:426 +0x80
github.com/convox/rack/client.(*Client).Get(0x0, 0x6301d7, 0x7, 0x5356e0, 0xc4202840c0, 0x0, 0x0)
/tmp/release.jHJRd/src/github.com/convox/rack/client/client.go:46 +0xb1
github.com/convox/rack/client.(*Client).GetSystem(0x0, 0x0, 0xc42019dc48, 0x1)
/tmp/release.jHJRd/src/github.com/convox/rack/client/system.go:25 +0x94
main.init.15.func1(0xc4201b0000)
/tmp/release.jHJRd/src/github.com/convox/rack/cmd/convox/main.go:23 +0xd8
github.com/convox/rack/vendor/gopkg.in/urfave/cli%2ev1.ShowVersion(0xc4201b0000)
/tmp/release.jHJRd/src/github.com/convox/rack/vendor/gopkg.in/urfave/cli.v1/help.go:166 +0x32
github.com/convox/rack/vendor/gopkg.in/urfave/cli%2ev1.(*App).Run(0xc420172300, 0xc42000a1c0, 0x2, 0x2, 0x0, 0x0)
/tmp/release.jHJRd/src/github.com/convox/rack/vendor/gopkg.in/urfave/cli.v1/app.go:204 +0x81b
main.main()
/tmp/release.jHJRd/src/github.com/convox/rack/cmd/convox/main.go:43 +0xa8
```

**Comment by soulshake** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Login should not be required for `doctor`, `--version` ("ERROR: must login first" + traceback)](https://trello.com/c/W7z95f9Q/1220-login-should-not-be-required-for-doctor-version-error-must-login-first-traceback)

**Comment by soulshake** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Rack segfault when not logged in](https://trello.com/c/PZXakHrK/2099-rack-segfault-when-not-logged-in)
