### ISSUE TITLE
Segfault on `convox -v`

### ISSUE THREAD

**Issue by rwos** [convox/rack#1418]
Just though I'd mention this:

```
$ convox -v
client: 20161122201731
ERROR: must login first
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x53c0a0]

goroutine 1 [running]:
panic(0x994f00, 0xc420010110)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/convox/rack/client.(*Client).request(0x0, 0xa3775a, 0x3, 0xa3aa27, 0x7, 0x0, 0x0, 0x9f6680, 0xc4201ea8c0, 0x32)
	/tmp/release.w4hPz/src/github.com/convox/rack/client/client.go:426 +0x80
github.com/convox/rack/client.(*Client).Get(0x0, 0xa3aa27, 0x7, 0x93f100, 0xc4202bc180, 0x0, 0x0)
	/tmp/release.w4hPz/src/github.com/convox/rack/client/client.go:46 +0xb1
github.com/convox/rack/client.(*Client).GetSystem(0x0, 0x0, 0xc4201d9c48, 0x1)
	/tmp/release.w4hPz/src/github.com/convox/rack/client/system.go:25 +0x94
main.init.15.func1(0xc4200b3e00)
	/tmp/release.w4hPz/src/github.com/convox/rack/cmd/convox/main.go:23 +0xd8
github.com/convox/rack/vendor/gopkg.in/urfave/cli%2ev1.ShowVersion(0xc4200b3e00)
	/tmp/release.w4hPz/src/github.com/convox/rack/vendor/gopkg.in/urfave/cli.v1/help.go:166 +0x32
github.com/convox/rack/vendor/gopkg.in/urfave/cli%2ev1.(*App).Run(0xc4201b2300, 0xc420096060, 0x2, 0x2, 0x0, 0x0)
	/tmp/release.w4hPz/src/github.com/convox/rack/vendor/gopkg.in/urfave/cli.v1/app.go:204 +0x81b
main.main()
	/tmp/release.w4hPz/src/github.com/convox/rack/cmd/convox/main.go:43 +0xa8
```

Should be the currently latest convox release (downloaded a few minutes ago). I'm running Debian:
```
$ uname -a
Linux easybox 4.3.0-1-amd64 #1 SMP Debian 4.3.3-7 (2016-01-19) x86_64 GNU/Linux
```

Let me know if you need anything else!

**Comment by rwos** [comment]
Ah, well, you already have that in https://github.com/convox/rack/issues/1408, sorry, didn't see that. Closing.

**Comment by soulshake** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Rack segfault when not logged in](https://trello.com/c/PZXakHrK/2099-rack-segfault-when-not-logged-in)
