### ISSUE TITLE
panic on local rack install with invalid input

### ISSUE THREAD

**Issue by jayjanssen** [convox/rack#2764]
using locall instead of local by mistake:

```
$ sudo convox rack install locall
panic:
assert: mock: I don't know what to return because the method call was unexpected.
	Either do Mock.On("SystemInstall").Return(...) first, or remove the SystemInstall() call.
	This method was unexpected:
		SystemInstall(structs.SystemInstallOptions)
		0: structs.SystemInstallOptions{Name:(*string)(nil), Output:(*stdcli.Writer)(0xc4200a6690), Parameters:map[string]string{}, Version:(*string)(nil)}
	at: [mock_Provider.go:1169 rack.go:127 command.go:71 engine.go:64 main.go:40 proc.go:198 asm_amd64.s:2361]

goroutine 1 [running]:
github.com/convox/rack/vendor/github.com/stretchr/testify/mock.(*Mock).Called(0xc420254280, 0xc42024c470, 0x1, 0x1, 0x59c2320, 0x4b5abf9, 0x7)
	/ext-go/1/src/github.com/convox/rack/vendor/github.com/stretchr/testify/mock/mock.go:310 +0x702
github.com/convox/rack/structs.(*MockProvider).SystemInstall(0xc420254280, 0x0, 0x5008e80, 0xc4200a6690, 0xc42024a510, 0x0, 0xc420254240, 0x0, 0x59c2320, 0x415fe24)
	/ext-go/1/src/github.com/convox/rack/structs/mock_Provider.go:1169 +0xe2
main.RackInstall(0xc420254240, 0x0, 0x0)
	/ext-go/1/src/github.com/convox/rack/cmd/convox/rack.go:127 +0x347
github.com/convox/rack/vendor/github.com/convox/stdcli.(*Command).Execute(0xc4202aa770, 0xc420030170, 0x1, 0x1, 0xc420030150, 0x3)
	/ext-go/1/src/github.com/convox/rack/vendor/github.com/convox/stdcli/command.go:71 +0x6a1
github.com/convox/rack/vendor/github.com/convox/stdcli.(*Engine).Execute(0xc42026e060, 0xc420030150, 0x3, 0x3, 0xc42009c058)
	/ext-go/1/src/github.com/convox/rack/vendor/github.com/convox/stdcli/engine.go:64 +0x393
main.main()
	/ext-go/1/src/github.com/convox/rack/cmd/convox/main.go:40 +0x6f
```

**Comment by jayjanssen** [comment]
minor issue.  this is the latest release: https://github.com/convox/rack/releases/tag/20180716161820
