### ISSUE TITLE
It would be nice to see failed cron launches in app logs

### ISSUE THREAD

**Issue by paulkernfeld** [convox/rack#2802]
Recently my team was working to debug some cron jobs that weren't running. By looking into CloudWatch logs, we were able to determine that this particular cron launch was failing because of insufficient available CPU in the ECS cluster (we also had an extra `*` in our cron spec). This debugging would probably be easier if we could see the cron launch failure in our app logs and in Papertrail.

It looks like Convox might be attempting to forward the logs from the lambda function somewhere, but failing.

```
START RequestId: 391224c4-906f-11e8-b782-b7d39e21e674 Version: $LATEST
2018-07-26T01:00:07.885Z	391224c4-906f-11e8-b782-b7d39e21e674	err { ResourceAlreadyExistsException: The specified log stream already exists
at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:48:27)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:683:14)
at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:685:12)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
message: 'The specified log stream already exists',
code: 'ResourceAlreadyExistsException',
time: 2018-07-26T01:00:07.884Z,
requestId: '3d4854d1-906f-11e8-b729-1542cc157e47',
statusCode: 400,
retryable: false,
retryDelay: 51.04253489508119 }
2018-07-26T01:00:07.983Z	391224c4-906f-11e8-b782-b7d39e21e674	skew=5138ms command=* ./bin/report_var result=failure reason=RESOURCE:CPU
2018-07-26T01:00:08.243Z	391224c4-906f-11e8-b782-b7d39e21e674	err2 { InvalidSequenceTokenException: The given sequenceToken is invalid. The next expected sequenceToken is: 49582773472938323831816196568079725757263709626630776370
at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:48:27)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:683:14)
at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:685:12)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
message: 'The given sequenceToken is invalid. The next expected sequenceToken is: 49582773472938323831816196568079725757263709626630776370',
code: 'InvalidSequenceTokenException',
time: 2018-07-26T01:00:08.242Z,
requestId: '3d7e3141-906f-11e8-a11d-79bf0ac44ac9',
statusCode: 400,
retryable: false,
retryDelay: 29.309782093437132 }
END RequestId: 391224c4-906f-11e8-b782-b7d39e21e674
REPORT RequestId: 391224c4-906f-11e8-b782-b7d39e21e674	Duration: 6724.71 ms	Billed Duration: 6800 ms Memory Size: 128 MB	Max Memory Used: 39 MB
```

**Comment by ddollar** [comment]
It could be nice to have cron-launches in the log but not super straight-forward since they are fired by Cloudwatch Events. I would accept this as a PR.
